/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Meu Computador
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        v1_lbl = new javax.swing.JLabel();
        v2_lbl = new javax.swing.JLabel();
        resul_lbl = new javax.swing.JLabel();
        v1_txt = new javax.swing.JTextField();
        v2_txt = new javax.swing.JTextField();
        resul_txt = new javax.swing.JTextField();
        soma_btn = new javax.swing.JButton();
        sub_btn = new javax.swing.JButton();
        div_btn = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sair_btn = new javax.swing.JButton();
        limpar_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 240, 245));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 240, 245));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 105, 180));
        jLabel2.setText("CALCULADORA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 10, 140, 40);

        v1_lbl.setBackground(new java.awt.Color(255, 102, 153));
        v1_lbl.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        v1_lbl.setForeground(new java.awt.Color(255, 105, 180));
        v1_lbl.setText("VALOR 1");
        jPanel1.add(v1_lbl);
        v1_lbl.setBounds(100, 100, 80, 14);

        v2_lbl.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        v2_lbl.setForeground(new java.awt.Color(255, 105, 180));
        v2_lbl.setText("VALOR 2");
        jPanel1.add(v2_lbl);
        v2_lbl.setBounds(100, 150, 66, 19);

        resul_lbl.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        resul_lbl.setForeground(new java.awt.Color(255, 105, 180));
        resul_lbl.setText("RESULTADO");
        jPanel1.add(resul_lbl);
        resul_lbl.setBounds(100, 200, 92, 19);
        jPanel1.add(v1_txt);
        v1_txt.setBounds(230, 100, 300, 20);
        jPanel1.add(v2_txt);
        v2_txt.setBounds(230, 150, 300, 20);
        jPanel1.add(resul_txt);
        resul_txt.setBounds(230, 200, 300, 20);

        soma_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        soma_btn.setForeground(new java.awt.Color(0, 206, 209));
        soma_btn.setText("+");
        soma_btn.setPreferredSize(new java.awt.Dimension(70, 20));
        soma_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soma_btnActionPerformed(evt);
            }
        });
        jPanel1.add(soma_btn);
        soma_btn.setBounds(230, 280, 60, 40);

        sub_btn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        sub_btn.setForeground(new java.awt.Color(0, 206, 209));
        sub_btn.setText("-");
        sub_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sub_btn);
        sub_btn.setBounds(310, 280, 60, 40);

        div_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        div_btn.setForeground(new java.awt.Color(0, 206, 209));
        div_btn.setText("/");
        div_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                div_btnActionPerformed(evt);
            }
        });
        jPanel1.add(div_btn);
        div_btn.setBounds(390, 280, 60, 40);

        multi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        multi.setForeground(new java.awt.Color(0, 206, 209));
        multi.setText("X");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        jPanel1.add(multi);
        multi.setBounds(470, 280, 60, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cute.gif"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 280, 170, 140);

        sair_btn.setBackground(new java.awt.Color(255, 240, 245));
        sair_btn.setForeground(new java.awt.Color(255, 240, 245));
        sair_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sair_btn);
        sair_btn.setBounds(560, 10, 65, 50);

        limpar_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clean-up.png"))); // NOI18N
        limpar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(limpar_btn);
        limpar_btn.setBounds(560, 360, 65, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(650, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void soma_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soma_btnActionPerformed
        Model.Funcoes_DAO.somar();
    }//GEN-LAST:event_soma_btnActionPerformed

    private void div_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_div_btnActionPerformed
        Model.Funcoes_DAO.dividir();
    }//GEN-LAST:event_div_btnActionPerformed

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair_btnActionPerformed

    private void sub_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btnActionPerformed
        Model.Funcoes_DAO.subtrair();
    }//GEN-LAST:event_sub_btnActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        Model.Funcoes_DAO.multiplicar();
    }//GEN-LAST:event_multiActionPerformed

    private void limpar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_btnActionPerformed
        Model.Funcoes_DAO.limpar();
    }//GEN-LAST:event_limpar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton div_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JButton limpar_btn;
    public static javax.swing.JButton multi;
    public static javax.swing.JLabel resul_lbl;
    public static javax.swing.JTextField resul_txt;
    public static javax.swing.JButton sair_btn;
    public static javax.swing.JButton soma_btn;
    public static javax.swing.JButton sub_btn;
    public static javax.swing.JLabel v1_lbl;
    public static javax.swing.JTextField v1_txt;
    public static javax.swing.JLabel v2_lbl;
    public static javax.swing.JTextField v2_txt;
    // End of variables declaration//GEN-END:variables
}
